from playwright.sync_api import sync_playwright

def run(playwright):
    browser = playwright.chromium.launch()
    page = browser.new_page()
    page.goto("http://localhost:3000/login")
    page.wait_for_load_state("networkidle")
    page.wait_for_selector('input[id="email"]')
    page.fill('input[id="email"]', "johndoe@example.com")
    page.fill('input[id="password"]', "strongpassword123")
    page.click('button[type="submit"]')
    page.wait_for_url("http://localhost:3000/dashboard")
    page.screenshot(path="jules-scratch/verification/dashboard.png")
    page.goto("http://localhost:3000/organizations")
    page.wait_for_load_state("networkidle")
    page.screenshot(path="jules-scratch/verification/organizations.png")
    page.goto("http://localhost:3000/sites")
    page.wait_for_load_state("networkidle")
    page.screenshot(path="jules-scratch/verification/sites.png")
    page.goto("http://localhost:3000/departments")
    page.wait_for_load_state("networkidle")
    page.screenshot(path="jules-scratch/verification/departments.png")
    page.goto("http://localhost:3000/devices")
    page.wait_for_load_state("networkidle")
    page.screenshot(path="jules-scratch/verification/devices.png")
    page.goto("http://localhost:3000/leaves")
    page.wait_for_load_state("networkidle")
    page.screenshot(path="jules-scratch/verification/leaves.png")
    page.goto("http://localhost:3000/reports")
    page.wait_for_load_state("networkidle")
    page.screenshot(path="jules-scratch/verification/reports.png")
    page.goto("http://localhost:3000/attendance")
    page.wait_for_load_state("networkidle")
    page.screenshot(path="jules-scratch/verification/attendance.png")
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
