// =================================================================
// # API SPECIFICATION TYPES
// # This file was auto-generated by an AI tool based on the OpenAPI specification.
// # Do not modify manually, as changes will be overwritten.
// =================================================================

// -----------------
// # Enums
// -----------------

export enum AttendanceType {
  In = "in",
  Out = "out",
}

export enum DeviceStatus {
  Online = "online",
  Offline = "offline",
  Maintenance = "maintenance",
}

export enum LeaveStatus {
  Pending = "pending",
  Approved = "approved",
  Rejected = "rejected",
  Cancelled = "cancelled",
}

export enum LeaveType {
  Annual = "annual",
  Sick = "sick",
  Maternity = "maternity",
  Paternity = "paternity",
  Unpaid = "unpaid",
  Other = "other",
}

export enum ReportFormat {
  PDF = "pdf",
  Excel = "excel",
  CSV = "csv",
}

export enum ReportPeriod {
  Daily = "daily",
  Weekly = "weekly",
  Monthly = "monthly",
  Custom = "custom",
}


// -----------------
// # Schemas
// -----------------

export interface User {
  email: string;
  full_name?: string | null;
  phone_number?: string | null;
  organization_id?: string | null;
  id: string;
  is_active: boolean;
  is_superuser: boolean;
  roles: Role[];
}

export interface UserInLogin {
  id: string;
  full_name?: string | null;
  email: string;
  is_superuser: boolean;
  roles: Role[];
}

export interface LoginCredentials {
  email: string;
  password: string;
}

export interface Token {
  access_token: string;
  refresh_token: string;
  token_type: string;
  user: UserInLogin;
}

// This is the old AuthResponse, renamed to Token to match the spec
export type AuthResponse = Token;

export interface RefreshTokenRequest {
  refresh_token: string;
}

export interface Role {
  name: string;
  description?: string | null;
  id: string;
  permissions: Permission[];
}

export interface Permission {
  name: string;
  description?: string | null;
  id: string;
}

export interface Organization {
  name: string;
  industry?: string | null;
  contact_email?: string | null;
  phone_number?: string | null;
  timezone: string;
  subscription_plan: string;
  is_active: boolean;
  settings?: Record<string, unknown> | null;
  id: string;
  sites: Site[];
}

export interface Site {
  name: string;
  location?: string | null;
  timezone: string;
  id: string;
  organization_id: string;
}

export interface Department {
  name: string;
  id: string;
  site_id: string;
  manager_id?: string | null;
}

export interface Employee {
  last_name: string;
  first_name: string;
  email: string;
  phone_number?: string | null;
  employee_id?: string | null;
  department?: string | null;
  position?: string | null;
  badge_number?: string | null;
  metadata?: Record<string, unknown> | null;
  id: string;
  organization_id: string;
  user_id?: string | null;
}

export interface Device {
  serial_number: string;
  model: string;
  status: DeviceStatus;
  organization_id: string;
  id: string;
}

export interface Attendance {
  timestamp: string; // "date-time"
  type: AttendanceType;
  geo?: string | null;
  extra_data?: Record<string, unknown> | null;
  id: string;
  employee_id: string;
  device_id?: string | null;
}

export interface Leave {
  leave_type: LeaveType;
  start_date: string; // "date"
  end_date: string; // "date"
  reason: string;
  id: string;
  employee_id: string;
  status: LeaveStatus;
  approver_id?: string | null;
  notes?: string | null;
  employee?: Employee | null;
  approver?: User | null;
}

// -----------------
// # Create & Update Schemas
// -----------------

export interface UserCreate {
  email: string;
  full_name?: string | null;
  phone_number?: string | null;
  organization_id?: string | null;
  password: string;
}

export interface UserUpdate {
  email?: string | null;
  full_name?: string | null;
  phone_number?: string | null;
  password?: string | null;
  is_active?: boolean | null;
}

export interface OrganizationCreate {
  name: string;
  industry?: string | null;
  contact_email?: string | null;
  phone_number?: string | null;
  timezone?: string;
  subscription_plan?: string;
  is_active?: boolean;
  settings?: Record<string, unknown> | null;
}

export interface OrganizationUpdate {
  name?: string | null;
  industry?: string | null;
  contact_email?: string | null;
  phone_number?: string | null;
  timezone?: string | null;
  subscription_plan?: string | null;
  is_active?: boolean | null;
  settings?: Record<string, unknown> | null;
}

export interface EmployeeCreate {
  last_name: string;
  first_name: string;
  email: string;
  phone_number?: string | null;
  employee_id?: string | null;
  department?: string | null;
  position?: string | null;
  badge_number?: string | null;
  metadata?: Record<string, unknown> | null;
  organization_id: string;
  user_id?: string | null;
}

export interface EmployeeUpdate {
  last_name?: string | null;
  first_name?: string | null;
  email?: string | null;
  phone_number?: string | null;
  employee_id?: string | null;
  department?: string | null;
  position?: string | null;
  badge_number?: string | null;
  metadata?: Record<string, unknown> | null;
}

export interface DepartmentCreate {
  name: string;
  site_id: string;
  manager_id?: string | null;
}

export interface DepartmentUpdate {
  name?: string | null;
  manager_id?: string | null;
}

export interface SiteCreate {
  name: string;
  location?: string | null;
  timezone?: string;
  organization_id: string;
}

export interface SiteUpdate {
  name?: string | null;
  location?: string | null;
  timezone?: string | null;
}

export interface DeviceCreate {
  serial_number: string;
  model?: string;
  status?: DeviceStatus;
  organization_id: string;
}

export interface DeviceUpdate {
  serial_number?: string | null;
  model?: string | null;
  status?: DeviceStatus | null;
}

export interface AttendanceCreate {
  timestamp: string; // "date-time"
  type: AttendanceType;
  geo?: string | null;
  extra_data?: Record<string, unknown> | null;
  employee_id: string;
  device_id?: string | null;
}

export interface LeaveCreate {
  leave_type: LeaveType;
  start_date: string; // "date"
  end_date: string; // "date"
  reason: string;
  employee_id: string;
}

export interface LeaveUpdate {
  status?: LeaveStatus | null;
  notes?: string | null;
}

export interface RoleCreate {
  name: string;
  description?: string | null;
}

export interface RoleUpdate {
  name?: string | null;
  description?: string | null;
}

export interface PermissionCreate {
  name: string;
  description?: string | null;
}

export interface PermissionUpdate {
  name?: string | null;
  description?: string | null;
}

// -----------------
// # API Error & Validation
// -----------------

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

// -----------------
// # Reporting & Misc
// -----------------

export interface ReportRequest {
  organization_id: number;
  period: ReportPeriod;
  start_date: string; // "date"
  end_date: string; // "date"
  format?: ReportFormat;
  employee_ids?: number[] | null;
  department?: string | null;
  include_charts?: boolean;
}

export interface AttendanceReportRow {
  employee_id: string; // "uuid"
  employee_name: string;
  badge_id: string;
  department?: string | null;
  total_days: number;
  present_days: number;
  absent_days: number;
  late_days: number;
  on_leave_days: number;
  attendance_rate: number;
  total_hours: number;
}

export interface AttendanceReport {
  organization_name: string;
  period: string;
  start_date: string; // "date"
  end_date: string; // "date"
  total_employees: number;
  rows: AttendanceReportRow[];
  summary: Record<string, unknown>;
}

// -----------------
// # Pagination (Generic)
// -----------------

export interface PaginationParams {
  skip?: number;
  limit?: number;
  search?: string;
  sort_by?: string;
  sort_order?: "asc" | "desc";
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  skip: number;
  limit: number;
}