// =================================================================
// # API SPECIFICATION TYPES
// # This file was auto-generated by an AI tool based on the OpenAPI specification.
// # Do not modify manually, as changes will be overwritten.
// =================================================================

// -----------------
// # Enums
// -----------------

export enum AttendanceType {
  In = "in",
  Out = "out",
}

export enum DeviceStatus {
  Online = "online",
  Offline = "offline",
  Maintenance = "maintenance",
}

export enum LeaveStatus {
  Pending = "pending",
  Approved = "approved",
  Rejected = "rejected",
  Cancelled = "cancelled",
}

export enum LeaveType {
  Annual = "annual",
  Sick = "sick",
  Maternity = "maternity",
  Paternity = "paternity",
  Unpaid = "unpaid",
  Other = "other",
}

export enum ReportFormat {
  PDF = "pdf",
  Excel = "excel",
  CSV = "csv",
}

export enum ReportPeriod {
  Daily = "daily",
  Weekly = "weekly",
  Monthly = "monthly",
  Custom = "custom",
}

// -----------------
// # Schemas
// -----------------

export interface User {
  email: string;
  full_name?: string | null;
  phone_number?: string | null;
  organization_id?: string | null;
  id: string;
  is_active: boolean;
  is_superuser: boolean;
  roles: Role[];
}

export interface UserInLogin {
  id: string;
  full_name?: string | null;
  email: string;
  is_superuser: boolean;
  roles: Role[];
}

export interface Token {
  access_token: string;
  refresh_token: string;
  token_type: string;
  user: UserInLogin;
}

export interface RefreshTokenRequest {
  refresh_token: string;
}

export interface Role {
  name: string;
  description?: string | null;
  id: string;
  permissions: Permission[];
}

export interface Permission {
  name: string;
  description?: string | null;
  id: string;
}

export interface Organization {
  name: string;
  description?: string | null;
  email?: string | null;
  phone?: string | null;
  timezone: string;
  plan?: string | null;
  is_active: boolean;
  id: string;
  sites_count: number;
  employees_count: number;
  users_count: number;
}

export interface SiteOrganization {
  name: string;
  description?: string | null;
  email?: string | null;
  phone?: string | null;
  timezone: string;
  plan?: string | null;
  is_active: boolean;
  id: string;
}

export interface Site {
  name: string;
  address?: string | null;
  timezone: string;
  id: string;
  organization?: SiteOrganization | null;
  departments_count: number;
  employees_count: number;
  devices_count: number;
}

export interface DepartmentSite {
  id: string;
  name: string;
}

export interface DepartmentManager {
  id: string;
  first_name: string;
  last_name: string;
  full_name?: string | null;
}

export interface Department {
  name: string;
  id: string;
  site?: DepartmentSite | null;
  manager?: DepartmentManager | null;
  employees_count: number;
}

export interface EmployeeDepartment {
  name: string;
  id: string;
}

export interface EmployeeSite {
  name: string;
  address?: string | null;
  timezone: string;
  id: string;
}

export interface EmployeeOrganization {
  name: string;
  description?: string | null;
  email?: string | null;
  phone?: string | null;
  timezone: string;
  plan?: string | null;
  is_active: boolean;
  id: string;
}

export interface EmployeeUser {
  email: string;
  full_name?: string | null;
  phone_number?: string | null;
  organization_id?: string | null;
  id: string;
  is_active: boolean;
}

export interface Employee {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string | null;
  employee_number?: string | null;
  position?: string | null;
  badge_id?: string | null;
  id: string;
  status: string;
  department?: EmployeeDepartment | null;
  site?: EmployeeSite | null;
  organization?: EmployeeOrganization | null;
  user?: EmployeeUser | null;
}

export interface DeviceOrganization {
  name: string;
  description?: string | null;
  email?: string | null;
  phone?: string | null;
  timezone: string;
  plan?: string | null;
  is_active: boolean;
  id: string;
}

export interface DeviceSite {
  name: string;
  address?: string | null;
  timezone: string;
  id: string;
}

export interface Device {
  serial_number: string;
  type: string;
  status: DeviceStatus;
  id: string;
  organization?: DeviceOrganization | null;
  site?: DeviceSite | null;
  last_attendance_timestamp?: string | null; // "date-time"
  daily_attendance_count: number;
}

export interface AttendanceEmployee {
  id: string;
  first_name: string;
  last_name: string;
  employee_number?: string | null;
}

export interface AttendanceDevice {
  id: string;
  serial_number: string;
  type: string;
}

export interface Attendance {
  timestamp: string; // "date-time"
  type: AttendanceType;
  geo?: string | null;
  extra_data?: Record<string, unknown> | null;
  id: string;
  duration?: string | null;
  employee?: AttendanceEmployee | null;
  device?: AttendanceDevice | null;
}

export interface LeaveDepartment {
  id: string;
  name: string;
}

export interface LeaveEmployee {
  id: string;
  first_name: string;
  last_name: string;
  department?: LeaveDepartment | null;
  full_name?: string | null;
}

export interface LeaveApprover {
  id: string;
  full_name?: string | null;
}

export interface Leave {
  leave_type: LeaveType;
  start_date: string; // "date"
  end_date: string; // "date"
  reason: string;
  notes?: string | null;
  id: string;
  status: LeaveStatus;
  duration: number;
  employee?: LeaveEmployee | null;
  approver?: LeaveApprover | null;
}

// -----------------
// # Create & Update Schemas
// -----------------

export interface UserCreate {
  email: string;
  full_name?: string | null;
  phone_number?: string | null;
  organization_id?: string | null;
  password: string;
}

export interface UserUpdate {
  email?: string | null;
  full_name?: string | null;
  phone_number?: string | null;
  password?: string | null;
  is_active?: boolean | null;
}

export interface OrganizationCreate {
  name: string;
  description?: string | null;
  email?: string | null;
  phone?: string | null;
  timezone?: string;
  plan?: string | null;
  is_active?: boolean;
}

export interface OrganizationUpdate {
  name?: string | null;
  description?: string | null;
  email?: string | null;
  phone?: string | null;
  timezone?: string | null;
  plan?: string | null;
  is_active?: boolean | null;
}

export interface EmployeeCreate {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string | null;
  employee_number?: string | null;
  position?: string | null;
  badge_id?: string | null;
  organization_id: string;
  department_id?: string | null;
  site_id?: string | null;
  user_id?: string | null;
}

export interface DepartmentCreate {
  name: string;
  site_id: string;
  manager_id?: string | null;
}

export interface DepartmentUpdate {
  name?: string | null;
  manager_id?: string | null;
}

export interface SiteCreate {
  name: string;
  address?: string | null;
  timezone?: string;
  organization_id: string;
}

export interface SiteUpdate {
  name?: string | null;
  address?: string | null;
  timezone?: string | null;
}

export interface DeviceCreate {
  serial_number: string;
  type?: string;
  status?: DeviceStatus;
  organization_id: string;
  site_id?: string | null;
}

export interface DeviceUpdate {
  serial_number?: string | null;
  type?: string | null;
  status?: DeviceStatus | null;
  site_id?: string | null;
}

export interface AttendanceCreate {
  timestamp: string; // "date-time"
  type: AttendanceType;
  geo?: string | null;
  extra_data?: Record<string, unknown> | null;
  employee_id: string;
  device_id?: string | null;
}

export interface LeaveCreate {
  leave_type: LeaveType;
  start_date: string; // "date"
  end_date: string; // "date"
  reason: string;
  notes?: string | null;
  employee_id: string;
}

export interface LeaveUpdate {
  status: LeaveStatus;
  notes?: string | null;
}

export interface RoleCreate {
  name: string;
  description?: string | null;
}

export interface RoleUpdate {
  name?: string | null;
  description?: string | null;
}

export interface PermissionCreate {
  name: string;
  description?: string | null;
}

export interface PermissionUpdate {
  name?: string | null;
  description?: string | null;
}

// -----------------
// # API Error & Validation
// -----------------

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

// -----------------
// # Reporting & Misc
// -----------------

export interface ReportRequest {
  organization_id: number;
  period: ReportPeriod;
  start_date: string; // "date"
  end_date: string; // "date"
  format?: ReportFormat;
  employee_ids?: number[] | null;
  department?: string | null;
  include_charts?: boolean;
}

export interface AttendanceReportRow {
  employee_id: string; // "uuid"
  employee_name: string;
  badge_id: string;
  department?: string | null;
  total_days: number;
  present_days: number;
  absent_days: number;
  late_days: number;
  on_leave_days: number;
  attendance_rate: number;
  total_hours: number;
}

export interface AttendanceReport {
  organization_name: string;
  period: string;
  start_date: string; // "date"
  end_date: string; // "date"
  total_employees: number;
  rows: AttendanceReportRow[];
  summary: Record<string, unknown>;
}

// -----------------
// # Pagination (Generic)
// -----------------

export interface PaginationParams {
  skip?: number;
  limit?: number;
  search?: string;
  sort_by?: string;
  sort_order?: "asc" | "desc";
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  skip: number;
  limit: number;
}